/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.doctors;

import dao.EncounterDao;
import dao.PatientDao;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.Patient;
import ui.MainMenu;

/**
 *
 * @author ZeyuLiao
 */
public class DoctorHomePage extends javax.swing.JPanel {

    EncounterDao eDao = new EncounterDao();
    PatientDao pDao = new PatientDao();
    Encounter e;
    private boolean flag = false;
    private final int id;
    /**
     * Creates new form HomePage
     * @param id
     * @throws java.lang.Exception
     */
    public DoctorHomePage(int id) throws Exception {
        initComponents();
        this.id = id;
        populateTable();
        if(jTableEncounter.getRowCount()!=0) setFlag(true);
        else setFlag(false);
    }

    public boolean isFlag() {
        return flag;
    }

    private void setFlag(boolean flag) {
        this.flag = flag;
    }
       

    private void populateTable() throws Exception{
        DefaultTableModel model = (DefaultTableModel) jTableEncounter.getModel();
        model.setRowCount(0);
        ArrayList<Encounter> elist = eDao.getAllEncounter();
        for (Encounter e : elist){
            if(id == e.getDoctorId() && e.getState()==false){
                Object[] row = new Object[5];
                Patient p = pDao.getPatientById(e.getPatientId());
                row[0] = e.getEncounterId();
                row[1] = p.getName();
                row[2] = e.getStartDate();
                row[3] = e.getSymptom();            
                model.addRow(row);  
                }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEncounter = new javax.swing.JTable();
        jPanelVitalSigns = new javax.swing.JPanel();
        jLabelBP = new javax.swing.JLabel();
        jLabelHBR = new javax.swing.JLabel();
        jLabelBS = new javax.swing.JLabel();
        jLabelWBC = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelStartDate = new javax.swing.JLabel();
        jLabelPatientId = new javax.swing.JLabel();
        jLabelDOB = new javax.swing.JLabel();
        jLabelCommunity = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSymptom = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDiagnose = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCheckVS = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonDiagnose = new javax.swing.JButton();

        setBackground(new java.awt.Color(149, 177, 182));
        setPreferredSize(new java.awt.Dimension(968, 429));

        jTableEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Encounter ID", "Name", "Date", "Symptom"
            }
        ));
        jScrollPane1.setViewportView(jTableEncounter);

        jPanelVitalSigns.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelBP.setText("Blood Pressure:");

        jLabelHBR.setText("Heart Beat Rate:");

        jLabelBS.setText("Blood Sugar:");

        jLabelWBC.setText("White Blood Cells:");

        javax.swing.GroupLayout jPanelVitalSignsLayout = new javax.swing.GroupLayout(jPanelVitalSigns);
        jPanelVitalSigns.setLayout(jPanelVitalSignsLayout);
        jPanelVitalSignsLayout.setHorizontalGroup(
            jPanelVitalSignsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVitalSignsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVitalSignsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWBC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHBR, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVitalSignsLayout.setVerticalGroup(
            jPanelVitalSignsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVitalSignsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHBR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBS, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelWBC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelName.setText("Name：");

        jLabelStartDate.setText("Community: ");

        jLabelPatientId.setText("Patient ID:");

        jLabelDOB.setText("Age:");

        jLabelCommunity.setText("Community：");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jLabelDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCommunity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDOB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPatientId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStartDate)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTextAreaSymptom.setColumns(20);
        jTextAreaSymptom.setRows(5);
        jScrollPane3.setViewportView(jTextAreaSymptom);

        jTextAreaDiagnose.setColumns(20);
        jTextAreaDiagnose.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDiagnose);

        jLabel1.setText("Symptom:");

        jLabel2.setText("Diagnose:");

        jButtonCheckVS.setText("Check Vital Signs");
        jButtonCheckVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckVSActionPerformed(evt);
            }
        });

        jButton1.setText("View Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonDiagnose.setText("Diagnose");
        jButtonDiagnose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiagnoseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCheckVS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDiagnose))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDiagnose, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButtonCheckVS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelVitalSigns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelVitalSigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDiagnoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiagnoseActionPerformed
        // TODO add your handling code here:
        e.setDiagnosis(jTextAreaDiagnose.getText());
        e.setEndDate(LocalDate.now());
        e.setState(true);
        if(jTableEncounter.getColumnCount()==0) MainMenu.notification(true);
        else MainMenu.notification(false);
        
        try {
            eDao.updateEncounter(e);
            System.out.println("ui.doctors.DoctorHomePage.jButtonDiagnoseActionPerformed()");   
        } catch (Exception ex) {
            Logger.getLogger(DoctorHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            populateTable();
            if(jTableEncounter.getColumnCount()==0) MainMenu.notification(true);
            else MainMenu.notification(false);            
        } catch (Exception ex) {
            Logger.getLogger(DoctorHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonDiagnoseActionPerformed

    private void jButtonCheckVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckVSActionPerformed
        // TODO add your handling code here:
        Random r = new Random();
        int bp = r.nextInt(40) + 80;
        int hr = r.nextInt(40) + 80;
        double bs = r.nextInt(10)*0.1 + 0.4;
        double wbc = r.nextInt(7)*0.1 + 0.4;
       
        e.setBlood_pressure(bp);
        e.setHeart_beat_rate(hr);
        e.setBlood_sugar(bs);
        e.setWhite_blood_cells(wbc);
        
        jLabelBP.setText("Blood Pressure: " + bp);
        jLabelHBR.setText("Heart Beat Rate: " + hr);
        jLabelBS.setText("Blood Sugar: " + String.valueOf(bs));
        jLabelWBC.setText("While Blood Cells: " + String.valueOf(wbc));       
        
    }//GEN-LAST:event_jButtonCheckVSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            int selectRowIndex = jTableEncounter.getSelectedRow();
            if(selectRowIndex <0){
                JOptionPane.showMessageDialog(this,"Please select a row to view details");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) jTableEncounter.getModel();
            int encounterId = Integer.parseInt(model.getValueAt(selectRowIndex,0).toString());
            e = eDao.getEncounterByEncounterId(encounterId);
            Patient patient = pDao.getPatientById(e.getPatientId());
            jLabelName.setText("Name: " + patient.getName());
            jLabelCommunity.setText("Community: " + patient.getCommunityName());
            jLabelDOB.setText("Date of Birth: " + patient.getDOB());
            jLabelPatientId.setText("Patient ID: " + e.getPatientId());
            jLabelStartDate.setText("Encounter Start Date: " + String.valueOf(e.getStartDate()));
            jTextAreaSymptom.setText(e.getSymptom());
            
        } catch (Exception ex) {
            Logger.getLogger(DoctorHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCheckVS;
    private javax.swing.JButton jButtonDiagnose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBP;
    private javax.swing.JLabel jLabelBS;
    private javax.swing.JLabel jLabelCommunity;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelHBR;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPatientId;
    private javax.swing.JLabel jLabelStartDate;
    private javax.swing.JLabel jLabelWBC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelVitalSigns;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableEncounter;
    private javax.swing.JTextArea jTextAreaDiagnose;
    private javax.swing.JTextArea jTextAreaSymptom;
    // End of variables declaration//GEN-END:variables
}
