/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import static java.awt.Image.SCALE_DEFAULT;
import javax.swing.ImageIcon;
import ui.doctors.DoctorProfilePage;
import ui.doctors.DoctorHomePage;
import ui.doctors.DoctorPatientPage;
import javax.swing.UIManager;
import ui.community.CommunityCRUD;
import ui.hospital.HospitalCrud;
import ui.hospitalAdmin.DoctorCrud;
import ui.patient.MyEncounter;
import ui.patient.Appointment;
import ui.patient.MyProfile;


/**
 *
 * @author ZeyuLiao
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     * @param flag different User type chosen in Entrance
     * @param id
     * @throws java.lang.Exception
     */
    public void MainMenu(int flag, int id) throws Exception {
//        try{
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//            }catch(Exception e){
//            System.out.println("主题出错");
//            e.printStackTrace();
//        }
        initComponents();
        setVisible(true);
        jLabelNotification.setVisible(false);
        switch (flag) {
            //Choose Patient
            case 0 -> {
                MyProfile mp = new MyProfile(id);
                jTabbedPaneMenu.addTab("My Profile",new javax.swing.ImageIcon("src//icon//heroicons-ui_63.png"),mp);
                Appointment ap = new Appointment(id);
                jTabbedPaneMenu.addTab("Appointment", new javax.swing.ImageIcon("src//icon//icon_home.png"), ap);
                //jTabbedPaneMenu.addTab("Appointment", ap);
                MyEncounter me = new MyEncounter(id);
                jTabbedPaneMenu.addTab("My Encounter", new javax.swing.ImageIcon("src//icon//icon_home.png"), me);

                
            }
            //Choose Doctor
            case 1 -> {
                DoctorHomePage hp = new DoctorHomePage(id);
                DoctorProfilePage pp = new DoctorProfilePage(id);
                DoctorPatientPage pap = new DoctorPatientPage();
                jLabelNotification.setVisible(hp.isFlag());
                jTabbedPaneMenu.addTab("", new javax.swing.ImageIcon("src//icon//icon_home.png"), hp);
                jTabbedPaneMenu.addTab("", new javax.swing.ImageIcon("src//icon//icon_patient.png"), pap);
                jTabbedPaneMenu.addTab("", new javax.swing.ImageIcon("src//icon//icon_profile.png"), pp);
                
            }
            //Choose Hospital Admin
            case 2 -> {
                DoctorCrud dc = new DoctorCrud();
                jTabbedPaneMenu.addTab("", new javax.swing.ImageIcon("src//icon//icon_patient.png"), dc);
                
            }
            //Choose Community Admin
            case 3 ->{
               HospitalCrud hc = new HospitalCrud();
               jTabbedPaneMenu.addTab("", new javax.swing.ImageIcon("src//icon//icon_home.png"), hc);
            }
            //Choose System Admin
            default -> {
                CommunityCRUD cc = new CommunityCRUD();
                 jTabbedPaneMenu.addTab("", new javax.swing.ImageIcon("src//icon//icon_home.png"), cc);
                
            }
        }       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        static public void notification(boolean flag){
        jLabelNotification.setVisible(flag);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHead = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNotification = new javax.swing.JLabel();
        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanelNavigator = new javax.swing.JPanel();
        jButtonChangeAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(300, 150));

        jPanelHead.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHead.setLayout(null);

        jPanel1.setLayout(null);

        jLabelNotification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelNotification);
        jLabelNotification.setBounds(0, 0, 20, 20);
        ImageIcon not = new ImageIcon("src//icon//icon_reddot.png");
        not.setImage(not.getImage().getScaledInstance(jLabelNotification.getWidth(),jLabelNotification.getHeight(),SCALE_DEFAULT));
        jLabelNotification.setIcon(not);

        jTabbedPaneMenu.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPaneMenu.setAlignmentX(1.0F);
        jTabbedPaneMenu.setAlignmentY(1.0F);
        jTabbedPaneMenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTabbedPaneMenu.setNextFocusableComponent(this);
        jPanel1.add(jTabbedPaneMenu);
        jTabbedPaneMenu.setBounds(0, 0, 1000, 440);
        jTabbedPaneMenu.getAccessibleContext().setAccessibleName("");

        jPanelNavigator.setBackground(new java.awt.Color(149, 177, 182));
        jPanelNavigator.setLayout(null);

        jButtonChangeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeAccountActionPerformed(evt);
            }
        });
        jPanelNavigator.add(jButtonChangeAccount);
        jButtonChangeAccount.setBounds(950, 10, 40, 40);
        ImageIcon logout = new ImageIcon("src//icon//icon_ChangeAccount.png");
        logout.setImage(logout.getImage().getScaledInstance(jButtonChangeAccount.getWidth(),jButtonChangeAccount.getHeight(),SCALE_DEFAULT));
        jButtonChangeAccount.setIcon(logout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNavigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHead, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHead, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChangeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeAccountActionPerformed
        // TODO add your handling code here:
        Entrance et = new Entrance();
        et.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonChangeAccountActionPerformed

//    /**
//     * @param flag different
//     */
//    public void MainMenu(int flag) {
//        /* Set the Nimbus look and feel */
////        try{
////            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
////            }catch(Exception e){
////            System.out.println("Error in theme");
////            e.printStackTrace();
////            }
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangeAccount;
    public static javax.swing.JLabel jLabelNotification;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JPanel jPanelNavigator;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    // End of variables declaration//GEN-END:variables
}
